# Generated by Django 6.0.2 on 2026-02-23 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicdb", "0008_widen_discogs_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackSpotifyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_id", models.CharField(max_length=64)),
                ("track_title", models.CharField(max_length=512)),
                ("spotify_track_id", models.CharField(max_length=64)),
                ("spotify_uri", models.CharField(blank=True, max_length=128)),
                ("spotify_name", models.CharField(blank=True, max_length=512)),
                ("spotify_artists", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_spotify_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["release_id", "track_title"],
                "unique_together": {("user", "release_id", "track_title")},
            },
        ),
    ]
