# Generated by Django 6.0.2 on 2026-04-05 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0011_remove_albumoverview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSpotifyImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicbrainz_artist_id', models.CharField(max_length=64)),
                ('image_url', models.TextField()),
                ('spotify_artist_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_spotify_image_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['musicbrainz_artist_id'],
                'unique_together': {('user', 'musicbrainz_artist_id')},
            },
        ),
    ]
