# Generated by Django 6.0.2 on 2026-04-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0012_artist_spotify_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistspotifyimagelink',
            name='discogs_artist_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
