# Generated by Django 6.0.2 on 2026-06-01 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0013_artist_image_link_discogs_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseGroupImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicbrainz_release_group_id', models.CharField(max_length=64)),
                ('image_url', models.TextField()),
                ('spotify_album_id', models.CharField(blank=True, max_length=64)),
                ('discogs_release_id', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_group_image_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['musicbrainz_release_group_id'],
                'unique_together': {('user', 'musicbrainz_release_group_id')},
            },
        ),
    ]
