import { useMemo } from "react";

function buildHeaderContext(args) {
  return {
    spotifyToken: args.spotifyToken,
    spotifyConnectionStatus: args.spotifyConnectionStatus,
    deviceId: args.deviceId,
    isPlaying: args.isPlaying,
    currentTrack: args.currentTrack,
    togglePlayback: args.togglePlayback,
    handleSpotifyLogin: args.handleSpotifyLogin,
    viewListId: args.viewListId,
    onViewListChange: args.resetOnViewSwitch,
    allListsForView: args.allListsForView,
    logout: args.logout,
  };
}

function buildSearchSidebarContext(args) {
  return {
    handleSubmit: args.handleSubmit,
    searchType: args.searchType,
    setSearchType: args.setSearchType,
    query: args.query,
    setQuery: args.setQuery,
    loading: args.loading,
    viewListId: args.viewListId,
    filterArtist: args.filterArtist,
    setFilterArtist: args.setFilterArtist,
    filterYear: args.filterYear,
    setFilterYear: args.setFilterYear,
    filterYearFrom: args.filterYearFrom,
    setFilterYearFrom: args.setFilterYearFrom,
    filterYearTo: args.filterYearTo,
    setFilterYearTo: args.setFilterYearTo,
    allowDigitsOnly: args.allowDigitsOnly,
    error: args.error,
    spotifyPlaylistsLoading: args.spotifyPlaylistsLoading,
    spotifyToken: args.spotifyToken,
    spotifyPlaylists: args.spotifyPlaylists,
    selectedPlaylistId: args.selectedPlaylistId,
    setSelectedPlaylistId: args.setSelectedPlaylistId,
    setSelectedItem: args.setSelectedItem,
    setDetailData: args.setDetailData,
    listViewData: args.listViewData,
    listViewLoading: args.listViewLoading,
    handleItemClick: args.handleItemClick,
    results: args.results,
    selectedItem: args.selectedItem,
  };
}

function buildPlaylistDetailContext(args) {
  return {
    playlistTracksLoading: args.playlistTracksLoading,
    playlistTracksData: args.playlistTracksData,
    deviceId: args.deviceId,
    spotifyToken: args.spotifyToken,
    playTrack: args.playTrack,
  };
}

function buildListModalContext(args) {
  return {
    listLoading: args.listLoading,
    lists: args.lists,
    selectedListIds: args.selectedListIds,
    toggleListSelection: args.toggleListSelection,
    handleCreateList: args.handleCreateList,
    newListName: args.newListName,
    setNewListName: args.setNewListName,
    listError: args.listError,
    handleAddToLists: args.handleAddToLists,
    handleCloseListModal: args.handleCloseListModal,
  };
}

function buildSpotifySearchModalContext(args) {
  return {
    closeSpotifySearchModal: args.closeSpotifySearchModal,
    handleSpotifySearch: args.handleSpotifySearch,
    spotifySearchQuery: args.spotifySearchQuery,
    setSpotifySearchQuery: args.setSpotifySearchQuery,
    spotifySearchLoading: args.spotifySearchLoading,
    spotifySearchResults: args.spotifySearchResults,
    handleSelectSpotifyTrack: args.handleSelectSpotifyTrack,
    spotifySearchFetched: args.spotifySearchFetched,
  };
}

function buildDetailPanelContext(args) {
  return {
    detailLoading: args.detailLoading,
    detailData: args.detailData,
    selectedItem: args.selectedItem,
    albumArtReady: args.albumArtReady,
    albumArtRetryKey: args.albumArtRetryKey,
    setAlbumArtRetryKey: args.setAlbumArtRetryKey,
    handleAddToList: args.handleAddToList,
    spotifyMatching: args.spotifyMatching,
    autoplay: args.autoplay,
    setAutoplay: args.setAutoplay,
    tracklistFilter: args.tracklistFilter,
    setTracklistFilter: args.setTracklistFilter,
    getDisplayLikeState: args.getDisplayLikeState,
    spotifyMatches: args.spotifyMatches,
    currentTrack: args.currentTrack,
    playbackDuration: args.playbackDuration,
    playbackPosition: args.playbackPosition,
    getTrackKey: args.getTrackKey,
    handleTrackRowClick: args.handleTrackRowClick,
    playTrack: args.playTrack,
    openSpotifySearchModal: args.openSpotifySearchModal,
    toggleLikeTrack: args.toggleLikeTrack,
    spotifyToken: args.spotifyToken,
    overviewLoading: args.overviewLoading,
    overview: args.overview,
    overviewError: args.overviewError,
  };
}

export function useAppContextValue(args) {
  const {
    spotifyToken,
    spotifyConnectionStatus,
    deviceId,
    isPlaying,
    currentTrack,
    togglePlayback,
    handleSpotifyLogin,
    viewListId,
    resetOnViewSwitch,
    allListsForView,
    logout,
    handleSubmit,
    searchType,
    setSearchType,
    query,
    setQuery,
    loading,
    filterArtist,
    setFilterArtist,
    filterYear,
    setFilterYear,
    filterYearFrom,
    setFilterYearFrom,
    filterYearTo,
    setFilterYearTo,
    allowDigitsOnly,
    error,
    spotifyPlaylistsLoading,
    spotifyPlaylists,
    selectedPlaylistId,
    setSelectedPlaylistId,
    setSelectedItem,
    setDetailData,
    listViewData,
    listViewLoading,
    handleItemClick,
    results,
    selectedItem,
    playlistTracksLoading,
    playlistTracksData,
    playTrack,
    listLoading,
    lists,
    selectedListIds,
    toggleListSelection,
    handleCreateList,
    newListName,
    setNewListName,
    listError,
    handleAddToLists,
    handleCloseListModal,
    closeSpotifySearchModal,
    handleSpotifySearch,
    spotifySearchQuery,
    setSpotifySearchQuery,
    spotifySearchLoading,
    spotifySearchResults,
    handleSelectSpotifyTrack,
    spotifySearchFetched,
    detailLoading,
    detailData,
    albumArtReady,
    albumArtRetryKey,
    setAlbumArtRetryKey,
    handleAddToList,
    spotifyMatching,
    autoplay,
    setAutoplay,
    tracklistFilter,
    setTracklistFilter,
    getDisplayLikeState,
    spotifyMatches,
    playbackDuration,
    playbackPosition,
    getTrackKey,
    handleTrackRowClick,
    openSpotifySearchModal,
    toggleLikeTrack,
    overviewLoading,
    overview,
    overviewError,
  } = args;

  return useMemo(
    () => ({
      header: buildHeaderContext({
        spotifyToken,
        spotifyConnectionStatus,
        deviceId,
        isPlaying,
        currentTrack,
        togglePlayback,
        handleSpotifyLogin,
        viewListId,
        resetOnViewSwitch,
        allListsForView,
        logout,
      }),
      searchSidebar: buildSearchSidebarContext({
        handleSubmit,
        searchType,
        setSearchType,
        query,
        setQuery,
        loading,
        viewListId,
        filterArtist,
        setFilterArtist,
        filterYear,
        setFilterYear,
        filterYearFrom,
        setFilterYearFrom,
        filterYearTo,
        setFilterYearTo,
        allowDigitsOnly,
        error,
        spotifyPlaylistsLoading,
        spotifyToken,
        spotifyPlaylists,
        selectedPlaylistId,
        setSelectedPlaylistId,
        setSelectedItem,
        setDetailData,
        listViewData,
        listViewLoading,
        handleItemClick,
        results,
        selectedItem,
      }),
      playlistDetail: buildPlaylistDetailContext({
        playlistTracksLoading,
        playlistTracksData,
        deviceId,
        spotifyToken,
        playTrack,
      }),
      listModal: buildListModalContext({
        listLoading,
        lists,
        selectedListIds,
        toggleListSelection,
        handleCreateList,
        newListName,
        setNewListName,
        listError,
        handleAddToLists,
        handleCloseListModal,
      }),
      spotifySearchModal: buildSpotifySearchModalContext({
        closeSpotifySearchModal,
        handleSpotifySearch,
        spotifySearchQuery,
        setSpotifySearchQuery,
        spotifySearchLoading,
        spotifySearchResults,
        handleSelectSpotifyTrack,
        spotifySearchFetched,
      }),
      detailPanel: buildDetailPanelContext({
        detailLoading,
        detailData,
        selectedItem,
        albumArtReady,
        albumArtRetryKey,
        setAlbumArtRetryKey,
        handleAddToList,
        spotifyMatching,
        autoplay,
        setAutoplay,
        tracklistFilter,
        setTracklistFilter,
        getDisplayLikeState,
        spotifyMatches,
        currentTrack,
        playbackDuration,
        playbackPosition,
        getTrackKey,
        handleTrackRowClick,
        playTrack,
        openSpotifySearchModal,
        toggleLikeTrack,
        spotifyToken,
        overviewLoading,
        overview,
        overviewError,
      }),
    }),
    [
      spotifyToken,
      spotifyConnectionStatus,
      deviceId,
      isPlaying,
      currentTrack,
      togglePlayback,
      handleSpotifyLogin,
      viewListId,
      resetOnViewSwitch,
      allListsForView,
      logout,
      handleSubmit,
      searchType,
      setSearchType,
      query,
      setQuery,
      loading,
      filterArtist,
      setFilterArtist,
      filterYear,
      setFilterYear,
      filterYearFrom,
      setFilterYearFrom,
      filterYearTo,
      setFilterYearTo,
      allowDigitsOnly,
      error,
      spotifyPlaylistsLoading,
      spotifyPlaylists,
      selectedPlaylistId,
      setSelectedPlaylistId,
      setSelectedItem,
      setDetailData,
      listViewData,
      listViewLoading,
      handleItemClick,
      results,
      selectedItem,
      playlistTracksLoading,
      playlistTracksData,
      playTrack,
      listLoading,
      lists,
      selectedListIds,
      toggleListSelection,
      handleCreateList,
      newListName,
      setNewListName,
      listError,
      handleAddToLists,
      handleCloseListModal,
      closeSpotifySearchModal,
      handleSpotifySearch,
      spotifySearchQuery,
      setSpotifySearchQuery,
      spotifySearchLoading,
      spotifySearchResults,
      handleSelectSpotifyTrack,
      spotifySearchFetched,
      detailLoading,
      detailData,
      albumArtReady,
      albumArtRetryKey,
      setAlbumArtRetryKey,
      handleAddToList,
      spotifyMatching,
      autoplay,
      setAutoplay,
      tracklistFilter,
      setTracklistFilter,
      getDisplayLikeState,
      spotifyMatches,
      playbackDuration,
      playbackPosition,
      getTrackKey,
      handleTrackRowClick,
      openSpotifySearchModal,
      toggleLikeTrack,
      overviewLoading,
      overview,
      overviewError,
    ],
  );
}
