from django.urls import path
from .views import (
    AlbumOverviewView,
    ConsumedAlbumView,
    ConsumedBackfillView,
    ConsumedListView,
    ConsumedTitlesView,
    DetailAPIView,
    EspeciallyLikedTrackView,
    EspeciallyLikedTracksView,
    ListDetailView,
    ListItemsCheckView,
    ListItemsView,
    ListsView,
    ManualSpotifyMatchView,
    ManualSpotifyMatchesView,
    SearchAPIView,
)

urlpatterns = [
    path("", SearchAPIView.as_view(), name="search"),
    path("detail/", DetailAPIView.as_view(), name="detail"),
    path("album-overview/", AlbumOverviewView.as_view(), name="album-overview"),
    path("consumed/", ConsumedAlbumView.as_view(), name="consumed"),
    path("consumed-titles/", ConsumedTitlesView.as_view(), name="consumed-titles"),
    path("consumed-list/", ConsumedListView.as_view(), name="consumed-list"),
    path("consumed-backfill/", ConsumedBackfillView.as_view(), name="consumed-backfill"),
    path("lists/", ListsView.as_view(), name="lists"),
    path("lists/<int:list_id>/", ListDetailView.as_view(), name="list-detail"),
    path("lists/items/", ListItemsView.as_view(), name="list-items"),
    path("lists/items/check/", ListItemsCheckView.as_view(), name="list-items-check"),
    path("manual-spotify-matches/", ManualSpotifyMatchesView.as_view(), name="manual-spotify-matches"),
    path("manual-spotify-match/", ManualSpotifyMatchView.as_view(), name="manual-spotify-match"),
    path("especially-liked-tracks/", EspeciallyLikedTracksView.as_view(), name="especially-liked-tracks"),
    path("especially-liked-track/", EspeciallyLikedTrackView.as_view(), name="especially-liked-track"),
]
