import { useMemo } from "react";

function buildSearchSidebarContext(args) {
  return {
    handleSubmit: args.handleSubmit,
    searchType: args.searchType,
    setSearchType: args.setSearchType,
    query: args.query,
    setQuery: args.setQuery,
    loading: args.loading,
    viewListId: args.viewListId,
    filterArtist: args.filterArtist,
    setFilterArtist: args.setFilterArtist,
    filterYear: args.filterYear,
    setFilterYear: args.setFilterYear,
    filterYearFrom: args.filterYearFrom,
    setFilterYearFrom: args.setFilterYearFrom,
    filterYearTo: args.filterYearTo,
    setFilterYearTo: args.setFilterYearTo,
    allowDigitsOnly: args.allowDigitsOnly,
    error: args.error,
    spotifyPlaylistsLoading: args.spotifyPlaylistsLoading,
    spotifyToken: args.spotifyToken,
    spotifyPlaylists: args.spotifyPlaylists,
    selectedPlaylistId: args.selectedPlaylistId,
    setSelectedPlaylistId: args.setSelectedPlaylistId,
    setSelectedItem: args.setSelectedItem,
    setDetailData: args.setDetailData,
    listViewData: args.listViewData,
    listViewLoading: args.listViewLoading,
    handleItemClick: args.handleItemClick,
    results: args.results,
    selectedItem: args.selectedItem,
  };
}

/** @param {Record<string, unknown>} args */
export function useSearchSidebarContextValue(args) {
  const {
    handleSubmit,
    searchType,
    setSearchType,
    query,
    setQuery,
    loading,
    viewListId,
    filterArtist,
    setFilterArtist,
    filterYear,
    setFilterYear,
    filterYearFrom,
    setFilterYearFrom,
    filterYearTo,
    setFilterYearTo,
    allowDigitsOnly,
    error,
    spotifyPlaylistsLoading,
    spotifyToken,
    spotifyPlaylists,
    selectedPlaylistId,
    setSelectedPlaylistId,
    setSelectedItem,
    setDetailData,
    listViewData,
    listViewLoading,
    handleItemClick,
    results,
    selectedItem,
  } = args;
  return useMemo(
    () =>
      buildSearchSidebarContext({
        handleSubmit,
        searchType,
        setSearchType,
        query,
        setQuery,
        loading,
        viewListId,
        filterArtist,
        setFilterArtist,
        filterYear,
        setFilterYear,
        filterYearFrom,
        setFilterYearFrom,
        filterYearTo,
        setFilterYearTo,
        allowDigitsOnly,
        error,
        spotifyPlaylistsLoading,
        spotifyToken,
        spotifyPlaylists,
        selectedPlaylistId,
        setSelectedPlaylistId,
        setSelectedItem,
        setDetailData,
        listViewData,
        listViewLoading,
        handleItemClick,
        results,
        selectedItem,
      }),
    [
      handleSubmit,
      searchType,
      setSearchType,
      query,
      setQuery,
      loading,
      viewListId,
      filterArtist,
      setFilterArtist,
      filterYear,
      setFilterYear,
      filterYearFrom,
      setFilterYearFrom,
      filterYearTo,
      setFilterYearTo,
      allowDigitsOnly,
      error,
      spotifyPlaylistsLoading,
      spotifyToken,
      spotifyPlaylists,
      selectedPlaylistId,
      setSelectedPlaylistId,
      setSelectedItem,
      setDetailData,
      listViewData,
      listViewLoading,
      handleItemClick,
      results,
      selectedItem,
    ],
  );
}
