# Generated by Django 6.0.2 on 2026-02-18 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discogs", "0006_list_listitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="list",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="list",
            name="list_type",
            field=models.CharField(
                choices=[
                    ("release", "Albums (releases)"),
                    ("person", "Persons (artists)"),
                ],
                default="release",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("user", "list_type", "name")},
        ),
    ]
